# Generated by Django 4.1 on 2022-08-25 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(default='', max_length=1000)),
                ('agent_ph', models.CharField(default='', max_length=1000)),
                ('agent_whts', models.CharField(default='', max_length=1000)),
                ('agent_desc', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('prop_id', models.AutoField(primary_key=True, serialize=False)),
                ('prop_name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('latest', models.BooleanField(default=True)),
                ('desc', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('loc_link', models.CharField(default='', max_length=1000)),
                ('prop_type', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('area', models.CharField(max_length=1000)),
                ('mark_price', models.CharField(max_length=1000)),
                ('our_price', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='static/images/')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.agent')),
                ('loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.location')),
            ],
        ),
        migrations.CreateModel(
            name='Prop_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='static/images/')),
                ('prop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
